import { configure } from '@storybook/react'

function loadStories() {
  require('./stories/components/Alert')
  require('./stories/components/Alert/Alert.js')
  require('./stories/components/Badge')
  require('./stories/components/Breadcrumb')
  require('./stories/components/Button')
  require('./stories/components/Card')
  require('./stories/components/Carousel')
  require('./stories/components/Collapse')
  require('./stories/components/Color')
  require('./stories/components/DatePicker')
  require('./stories/components/DateTime')
  require('./stories/components/Debugger')
  require('./stories/components/Dropdown')
  require('./stories/components/Error')
  require('./stories/components/Fade')
  require('./stories/components/Form')
  require('./stories/components/Icon')
  require('./stories/components/Input')
  require('./stories/components/Jumbotron')
  require('./stories/components/Label')
  require('./stories/components/Loader')
  require('./stories/components/ListGroup')
  require('./stories/components/Media')
  require('./stories/components/Misc')
  require('./stories/components/Modal')
  require('./stories/components/Nav')
  require('./stories/components/Pagination')
  require('./stories/components/Popover')
  require('./stories/components/Progress')
  require('./stories/components/Table')
  require('./stories/components/Tabs')
  require('./stories/components/Tooltip')
}

configure(loadStories, module)
